version: '3.4'
services:
  web:
    image: "{{Values.image}}"
    ports:
      - "{{Computed.bindUrl.hostname}}:{{Computed.bindUrl.port}}:{{'80' if Computed.bindUrl.scheme == 'http' else '443'}}"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

x-compose-me:
  templates:
    - ./nginx.conf
